/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendarCard: typeof import('@nutui/nutui-taro')['CalendarCard']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
